---
  name: "hello-world"
  version: "0.0.1"
  description: "Example component"
  author: "Ginetta"
  type: "angular"
  data:
    title: "Component title"
    age: 12
  options:
    size:
      values: ["big", "medium", "small"]
      default: "medium"
